# Generated by Django 3.2.3 on 2021-05-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210527_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Comptoir', 'Comptoir'), ('Mirale', 'Mirale'), ('Serie', 'Serie'), ('Vitrine', 'Vitrine'), ('Machine', 'Machine')], default='serie', max_length=20),
        ),
    ]
