# Generated by Django 3.2.3 on 2021-05-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Serie', 'Serie'), ('Mirale', 'Mirale'), ('Comptoir', 'Comptoir'), ('Vitrine', 'Vitrine'), ('Machine', 'Machine')], default='serie', max_length=20),
        ),
    ]
