# Generated by Django 3.2.3 on 2021-05-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vitrine', 'Vitrine'), ('Mirale', 'Mirale'), ('Serie', 'Serie'), ('Machine', 'Machine'), ('Comptoir', 'Comptoir')], default='serie', max_length=20),
        ),
    ]
