# Generated by Django 3.2.3 on 2021-05-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fournisseur',
            new_name='Fournisseurr',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Comptoir', 'Comptoir'), ('Vitrine', 'Vitrine'), ('Mirale', 'Mirale'), ('Machine', 'Machine'), ('Serie', 'Serie')], default='serie', max_length=20),
        ),
    ]
