# Generated by Django 3.2.3 on 2021-05-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210530_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Machine', 'Machine'), ('Comptoir', 'Comptoir'), ('Vitrine', 'Vitrine'), ('Mirale', 'Mirale'), ('Serie', 'Serie')], default='serie', max_length=20),
        ),
    ]
