# Generated by Django 3.2.3 on 2021-05-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mirale', 'Mirale'), ('Comptoir', 'Comptoir'), ('Machine', 'Machine'), ('Vitrine', 'Vitrine'), ('Serie', 'Serie')], default='serie', max_length=20),
        ),
    ]
