# Generated by Django 3.2.3 on 2021-05-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vitrine', 'Vitrine'), ('Machine', 'Machine'), ('Comptoir', 'Comptoir'), ('Mirale', 'Mirale'), ('Serie', 'Serie')], default='serie', max_length=20),
        ),
    ]
